name: flask-aws-ebn
env:
  EB_PACKAGE_S3_BUCKET_NAME : "myflask"
  EB_APPLICATION_NAME       : "myflask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"
  
  AWS_KEY                   : ${{ secrets.AWS_KEY }}
  AWS_SECRET_KEY            : ${{ secrets.AWS_SECRET_KEY }}
  
on:
  push:
    branches: [ master ]

jobs:
  ci_pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone the repo
        uses: actions/checkout@v2
      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy package
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

  cd_pipe:
    runs-on: ubuntu-latest
    needs: [ci_part]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: create new ebn 
        run : |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}", S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "version-${{ github.sha }}" \
          --description "Commit-SHA:${{ github.sha }}"

      -name: deploy to ebn
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "version-${{ github.sha }}"
