name: flask-aws-ebn
env:
  EB_PACKAGE_S3_BUCKET_NAME : "myflask"
  EB_APPLICATION_NAME       : "myflask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"
  
  AWS_KEY                   : ${{ secrets.AWS_KEY }}
  AWS_SECRET_KEY            : ${{ secrets.AWS_SECRET_KEY }}
  
on:
  push:
    branches: [ master ]

jobs:
  ci_pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone the repo
        uses: actions/checkout@v2
      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy package
        run : aws cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
